name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install verilator libevent-dev libjson-c-dev

    - name: Get Migen / LiteX / Cores
      run: |
        wget https://raw.githubusercontent.com/enjoy-digital/litex/main/litex_setup.py
        python3 litex_setup.py init install

    - name: Install the version being tested
      run: |
        python3 setup.py install

    - name: Get RISC-V toolchain
      run: |
        wget https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
        tar -xvf riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6.tar.gz
        echo "$PWD/riscv64-unknown-elf-gcc-20171231-x86_64-linux-centos6/bin" >> $GITHUB_PATH

    - name: Run tests
      run: |
        python setup.py test
