name: Python CI

on:
  push:
    branches:
      - '**'
      - '!dependabot/**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', 'pypy-3.8', 'pypy-3.9']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        if [ "${{ matrix.python-version }}" == "3.8" ]; then
          pip install cryptography==2.6.1
        fi
        pip install -r requirements.txt

    - name: Run script
      run: ci/travis.sh
