name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 10

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git build-essential automake libtool python3-dev gettext swig
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 --version
        echo compiling AutoBouquetsMaker enigma2 plugin
        python -m compileall .
        find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;
        flake8 --ignore=W191,E128,E501,E722 . --exit-zero
        echo done.
