name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.8, 3.7, 3.6, pypy-3.7-v7.3.3]
        include:
          - os: ubuntu-latest
            python-version: 3.7
            arch: arm64
          - os: ubuntu-latest
            python-version: 3.7
            arch: amd64

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.arch }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mock

    - name: Run tests
      run: python -m unittest discover -p '*_test.py'
