name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        django-version: [2.2, 3.0, 3.1, 3.2]
        include:
          - os: ubuntu-latest
            python-version: 3.6
            django-version: 2.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.7
            django-version: 2.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.8
            django-version: 2.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.9
            django-version: 2.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.6
            django-version: 3.0
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.7
            django-version: 3.0
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.8
            django-version: 3.0
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.9
            django-version: 3.0
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.6
            django-version: 3.1
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.7
            django-version: 3.1
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.8
            django-version: 3.1
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.9
            django-version: 3.1
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.6
            django-version: 3.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.7
            django-version: 3.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.8
            django-version: 3.2
            arch: ppc64le
          - os: ubuntu-latest
            python-version: 3.9
            django-version: 3.2
            arch: ppc64le

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tests
      env:
        TOXENV: py${{ matrix.python-version }}-django${{ matrix.django-version }}
      run: tox
