name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
        django-version:
          - "Django>=1.8,<1.9"
          - "Django>=1.9,<1.10"
          - "Django>=1.10,<1.11"
          - "Django>=1.11,<2.0"
          - "https://github.com/django/django/archive/main.tar.gz"
      exclude:
        - python-version: "3.6"
          django-version: "Django>=1.8,<1.9"
        - python-version: "3.6"
          django-version: "Django>=1.9,<1.10"
        - python-version: "3.6"
          django-version: "Django>=1.10,<1.11"
        - python-version: "3.6"
          django-version: "Django>=1.11,<2.0"
      allow_failures:
        - django-version: "https://github.com/django/django/archive/main.tar.gz"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls coverage
        pip install ${{ matrix.django-version }}
    - name: Run tests
      run: |
        coverage run runtests.py
        coverage report -m
    - name: Upload coverage to Coveralls
      if: success()
      run: |
        coverage combine
        coveralls
