name: CI

on:
  push:
    branches:
      - main
      - /^v\d+\.\d+(\.(\d|x)+)?(-\S*)?$/
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        include:
          - python-version: 3.8
            env: TOXENV="lint,docs"
          - python-version: 3.8
            env: TOXENV=django31-py38-all RUN_LIVE_TESTS=true
          - python-version: 3.7
            env: TOXENV=django31-py37-none
          - python-version: 3.7
            env: TOXENV=django31-py37-amazon_ses
          - python-version: 3.7
            env: TOXENV=django22-py37-all-old_urllib3
          - python-version: 3.7
            env: TOXENV=djangoDev-py37-all
            allow_failure: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run tests
        env:
          TOX_FORCE_IGNORE_OUTCOME: false
        run: tox
