name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, pypy3]
        toxenv:
          - pep8
          - placement
          - py37
          - py38
          - pypy3
          - py37-pytest
          - py37-failskip
          - py37-limit
          - py37-prefix
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install tox
      - name: Run Tox
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
