name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - python-version: "3.6"
            arch: ppc64le
          - python-version: "3.7"
            arch: ppc64le
          - python-version: "3.8"
            arch: ppc64le
          - python-version: "3.9"
            arch: ppc64le
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tests
      env:
        TOXENV: py${{ matrix.python-version }}
      run: tox -e $TOXENV
    - name: Upload coverage to Codecov
      if: success()
      env:
        TOXENV: coverage-report
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        tox -e coverage-report
        codecov
