name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10, 3.11]
        toxenv: [py37, py38, py39, py310, py311, pep8, docs, packaging]
        include:
          - python-version: 3.7
            toxenv: py37
          - python-version: 3.8
            toxenv: py38
          - python-version: 3.9
            toxenv: py39
          - python-version: 3.10
            toxenv: py310
          - python-version: 3.11
            toxenv: py311
          - python-version: 3.11
            toxenv: pep8
          - python-version: 3.11
            toxenv: docs
          - python-version: 3.11
            toxenv: packaging

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: pip install tox

    - name: Run Tox
      env:
        TOXENV: ${{ matrix.toxenv }}
      run: tox
