name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, 3.10, "3.x"]
        include:
          - python-version: "3.x"
            env: PRE: --pre
      allow_failures:
        - python-version: "3.x"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -v .
        python -m pip install ${{ matrix.env.PRE }} --upgrade pytest pytest-cov coverage

    - name: Run tests
      run: |
        coverage run run_tests.py
        coverage report -m

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
