name: Python package

on:
  push:
    branches:
      - '**'
      - '!queues'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]
        toxenv: [py37-dj32, py38-dj32, py39-dj32, py310-dj32]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage codecov coveralls tox
    - name: Run tests
      run: |
        ./bin/fake-server &
        tox -e ${{ matrix.toxenv }}
    - name: Upload coverage to Coveralls
      if: success()
      run: coveralls
    - name: Upload coverage to Codecov
      if: success()
      uses: codecov/codecov-action@v3

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref_type == 'tag' && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Build and publish
      env:
        TWINE_USERNAME: apsl
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        tox -e py310-dj32
        python -m pip install --upgrade build twine
        python -m build
        python -m twine upload dist/*
