name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        geos-version: ["3.6.4", "3.7.3", "3.8.1", "3.8.1"]
        numpy-version: ["1.13.3", "1.15.4", "1.17.5", "1.19.4"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        export GEOS_INSTALL=$HOME/geosinstall/geos-${{ matrix.geos-version }}
        ./ci/install_geos.sh
        pip install --disable-pip-version-check --upgrade pip
        pip install --upgrade wheel
        if [ "${{ matrix.geos-version }}" = "main" ]; then
          pip install --upgrade --pre Cython numpy pytest
        else
          pip install --upgrade Cython "numpy==${{ matrix.numpy-version }}" pytest
        fi
        export LD_LIBRARY_PATH=$GEOS_INSTALL/lib
        export PATH=$GEOS_INSTALL/bin:$PATH
        python setup.py build_ext --inplace
        pip install --no-deps -e .

    - name: Test with pytest
      run: pytest --doctest-modules
