name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7", "3.6"]
        django-version:
          - "Django>=1.11,<2.0"
          - "https://github.com/django/django/archive/main.tar.gz"
      exclude:
        - python-version: "2.7"
          django-version: "https://github.com/django/django/archive/main.tar.gz"
        - python-version: "3.6"
          django-version: "https://github.com/django/django/archive/main.tar.gz"
      allow_failures:
        - django-version: "https://github.com/django/django/archive/main.tar.gz"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coveralls coverage
        pip install ${{ matrix.django-version }}
    - name: Run tests
      run: |
        coverage run runtests.py
        coverage report -m
    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        coverage combine
        coveralls
