name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        env:
          - TOX_ENV=flake8
          - TOX_ENV=isort
          - DJANGO=dj22
          - DJANGO=dj30
          - DJANGO=dj31
          - DJANGO=dj32
    env:
      TOX_ENV: ${{ matrix.env.TOX_ENV }}
      DJANGO: ${{ matrix.env.DJANGO }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install coverage isort tox
        if [ "${{ matrix.python-version }}" == "3.8" ]; then echo "PY_VER=py38" >> $GITHUB_ENV; fi
        if [ "${{ matrix.python-version }}" == "3.9" ]; then echo "PY_VER=py39" >> $GITHUB_ENV; fi
        if [ "${{ matrix.python-version }}" == "3.10" ]; then echo "PY_VER=py310" >> $GITHUB_ENV; fi
        if [ "${{ matrix.python-version }}" == "3.11" ]; then echo "PY_VER=py311" >> $GITHUB_ENV; fi
        if [ "${{ env.DJANGO }}" != "" ]; then echo "TOX_ENV=${{ env.PY_VER }}" >> $GITHUB_ENV; fi
    - name: Run tests
      run: tox -e ${{ env.TOX_ENV }}
    - name: Upload coverage to Codecov
      if: success()
      run: bash <(curl -s https://codecov.io/bash)
