name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]
        env:
          - TOXENV=py38
          - TOXENV=py39
          - TOXENV=py310
          - TOXENV=py311
          - TOXENV=qa,doc

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools tox

    - name: Run tests
      env:
        TOXENV: ${{ matrix.env }}
      run: tox -v
