name: CI

on:
  push:
    branches:
      - main
      - /^v\d+\.\d+(\.(\d|x)+)?(-\S*)?$/
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy3]
        toxenv:
          - lint,docs
          - django20-py37-all
          - django20-py38-all
          - django20-pypy3-all
          - django21-py37-all
          - django21-py38-all
          - django21-pypy3-all
          - django22-py37-all
          - django22-py38-all
          - django22-pypy3-all
          - django30-py37-all
          - django30-py38-all
          - django30-pypy3-all
          - django31-py37-all
          - django31-py38-all
          - django31-pypy3-all
          - djangoDev-py37-all
          - django31-py37-none
          - django31-py37-amazon_ses
          - django22-py37-all-old_urllib3
      exclude:
        - python-version: 3.7
          toxenv: lint,docs
        - python-version: 3.8
          toxenv: lint,docs
        - python-version: 3.9
          toxenv: lint,docs
        - python-version: 3.9
          toxenv: django20-py37-all
        - python-version: 3.9
          toxenv: django20-py38-all
        - python-version: 3.9
          toxenv: django20-pypy3-all
        - python-version: 3.9
          toxenv: django21-py37-all
        - python-version: 3.9
          toxenv: django21-py38-all
        - python-version: 3.9
          toxenv: django21-pypy3-all
        - python-version: 3.9
          toxenv: django22-py37-all
        - python-version: 3.9
          toxenv: django22-py38-all
        - python-version: 3.9
          toxenv: django22-pypy3-all
        - python-version: 3.9
          toxenv: django30-py37-all
        - python-version: 3.9
          toxenv: django30-py38-all
        - python-version: 3.9
          toxenv: django30-pypy3-all
        - python-version: 3.9
          toxenv: django31-py37-all
        - python-version: 3.9
          toxenv: django31-py38-all
        - python-version: 3.9
          toxenv: django31-pypy3-all
        - python-version: 3.9
          toxenv: djangoDev-py37-all
        - python-version: 3.9
          toxenv: django31-py37-none
        - python-version: 3.9
          toxenv: django31-py37-amazon_ses
        - python-version: 3.9
          toxenv: django22-py37-all-old_urllib3
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run tox
      env:
        TOXENV: ${{ matrix.toxenv }}
        TOX_FORCE_IGNORE_OUTCOME: false
      run: tox
