name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, pypy-3.8, pypy-3.9]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache Hypothesis directory
      uses: actions/cache@v3
      with:
        path: ~/.hypothesis
        key: ${{ runner.os }}-hypothesis-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-hypothesis-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade --upgrade-strategy only-if-needed pytest
        pip install .

    - name: Run tests
      run: pytest

  notifications:
    email:
      if: failure()
      on_success: change
      on_failure: always
