name: Python package

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [2.7, 3.8]
        tox-env: [py27, py38]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tests
        env:
          TOX_ENV: ${{ matrix.tox-env }}
        run: tox -e $TOX_ENV
