name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "pypy3"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -e .
        pip install requests pytest-cov

    - name: Start services
      run: |
        docker-compose -f tests/config/docker-compose.yml up -d
        sleep 120
        ./tests/config/bootstrap

    - name: Run tests
      run: |
        pytest -v --cov=pygelf

    - name: Stop services
      if: always()
      run: docker-compose -f tests/config/docker-compose.yml down

    - name: Upload coverage to Coveralls
      if: success()
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: coveralls
