name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        env:
          - TOXENV=py36-django22,py36-django31,py36-django32
          - TOXENV=py37-django22,py37-django31,py37-django32
          - TOXENV=py38-django22,py38-django31,py38-django32,lint,coverage
          - TOXENV=py39-django22,py39-django31,py39-django32
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox codecov
      - name: Run tests
        env:
          TOXENV: ${{ matrix.env }}
        run: tox
      - name: Upload coverage to Codecov
        if: success()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: codecov
