name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.9]
        django-version: [">=2.2,<2.3", ">=3.0,<3.2", ">=3.2,<3.3"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install poetry
        poetry install -q
        poetry run pip install -q Django${{ matrix.django-version }}

    - name: Run tests
      run: poetry run python -m pytest
