name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit flake8 coverage liccheck
        pip install -r requirements.txt
        python setup.py bdist_wheel
        pip install dist/feedgen*

    - name: Run tests
      run: make test

    - name: Check licenses
      run: liccheck -s .licenses.ini

    - name: Run feedgen
      run: |
        python -m feedgen
        python -m feedgen atom
        python -m feedgen rss

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: |
        pip install python-coveralls
        coveralls
