name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, '3.x']
        with-opt-deps: [true, false]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        if [ "${{ matrix.with-opt-deps }}" = "true" ]; then
          pip install -r requirements.txt pytest
        fi
        git clone https://github.com/ProgVal/irctest.git
        echo "y" | pip uninstall limnoria || true
    - name: Install package
      run: python setup.py install
    - name: Run tests
      run: |
        supybot-test test -v --plugins-dir=./plugins/ --no-network
        if [ "${{ matrix.with-opt-deps }}" = "true" ] && [[ "${{ matrix.python-version }}" =~ ^3\.[4-9] ]]; then
          cd irctest
          pytest --controllers irctest.controllers.limnoria
        fi
