name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, pypy-3.9]
        toxenv:
          - pre-commit
          - py38-2.2
          - py39-2.2
          - pypy3-2.2
          - py38-3.0
          - py39-3.0
          - pypy3-3.0
          - py38-3.1
          - py39-3.1
          - pypy3-3.1
          - py38-3.2
          - py39-3.2
          - pypy3-3.2
          - py38-main
          - py39-main
          - pypy3-main
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage tox
      - name: Run tests
        env:
          TOXENV: ${{ matrix.toxenv }}
        run: tox
      - name: Upload coverage to Coveralls
        if: success()
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: coveralls
